@startuml

[*] --> Inactive: Create
Inactive --> Activating: activate (schema)
Activating --> Active: in - base (data)
Activating --> Invalid: invalidate
Active --> Active: in - update
Active --> Active: apply; out - update
Active --> Deactivating: deactivate
Active --> Invalid: invalidate
Deactivating --> Deactivating: in - update
Deactivating --> Deactivated: in - update and backlog empty
Deactivating --> Invalid: invalidate

Deactivated --> [*]
Invalid --> [*]

@enduml